# Generated by Django 3.2 on 2022-08-31 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculation',
            options={'ordering': ['-id']},
        ),
    ]
