# Generated by Django 3.2 on 2022-06-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20220611_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='date_uploaded',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tariff',
            name='date_uploaded',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
