# Generated by Django 3.2 on 2022-09-18 13:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_alter_calculation_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='id',
        ),
        migrations.AddField(
            model_name='tariff',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
