# Generated by Django 3.2 on 2022-09-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_auto_20220918_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='uuid',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
