# Generated by Django 3.2 on 2022-09-18 13:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_alter_tariff_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
