# Generated by Django 3.2 on 2022-09-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_alter_tariff_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='tariff',
            name='hscode',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
