# Generated by Django 3.2 on 2022-09-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_auto_20220918_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
